apiVersion: v1
kind: Service
metadata:
  name: games-eks
  labels:
    app: games-eks
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: games-eks
    protocol: TCP
  - name: "443"
    port: 443
    targetPort: games-eks
    protocol: TCP
  selector:
    app: games-eks
  type: LoadBalancer
